### ISSUE TITLE
Limitation to System.Reactive < 4.0.0 holds me from upgrading other packages (Akavache)

### ISSUE THREAD

**Issue by wierikr** [reactiveui/punchclock#21]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/punchclock . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Limitation to System.Reactive < 4.0.0

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Ugrade a project with System.Reactive, Fusillade, Punchclock & Akavache.
I need to upgrade Akavache, but this needs System.Reactive >= 4.0.0

**What is the expected behavior?**
Being able to upgrade my packages to the latest version.

**What is the motivation / use case for changing the behavior?**
I can't apply fixes in new versions of other packages, because PunchClock (& Fusillade) blocks this.

**Which versions of PunchClock, and which platform / OS are affected by this issue? Did this work in previous versions of PunchClock?**
v2.1.0. is affected. v2.0.0 does not mention the limitation, but I'm not sure wether it's safe to downgrade to this version in combination with System.Reactive > 4.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
No suggestions, because I don't know why the limitation is needed.

**Comment by glennawatson** [comment]
Fixed by v3.0.17
